name: codingchallenge_redandroid
description: Coding challenge Red Android - Houses of Thrones

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  dio: ^4.0.6
  retrofit: ^3.0.1+1

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  retrofit_generator: ^4.0.1
  flutter_lints: ^2.0.1

  test: ^1.21.1

flutter:
  uses-material-design: true
